In [11]:
from glob import glob
import subprocess
import os 
from nilearn.image import resample_to_img
import nibabel as nib
from tqdm import tqdm
from nimlab import datasets as nimds


from calvin_utils.nifti_utils.generate_nifti import nifti_from_matrix
from calvin_utils.file_utils.import_functions import GiiNiiFileImport


def downsample_image(input_path, output_path):
    """
    Function to downsample a 3D image to a new voxel size using a target affine.
    
    Args:
    input_path (str): Filepath to the input image.
    output_path (str): Filepath to save the output image.
    target_voxel_size (list): Target voxels to resample to.
    """
    # Load the image
    img = nib.load(input_path)
    mni_mask = nimds.get_img("mni_icbm152")
    
    # Downsample the image using the target affine
    resampled_img = resample_to_img(img, mni_mask)

    # Save the downsampled image
    nib.save(resampled_img, output_path)
# User-defined variables
root_dir = r"/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs"
file_pattern_1 = r"/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-R.nii"
file_pattern_2 = r"/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-L.nii"
output_file_pattern = r"sim-efield_model-simbio_hemi-bl.nii"

# Path to MNI template
mni_template_path = r"/Users/cu135/Dropbox (Partners HealthCare)/resources/mni_spaces/mni_icbm152_nlin_sym_09b_nifti/mni_icbm152_nlin_sym_09b/mni_icbm152_t1_tal_nlin_sym_09b_hires.nii"

for sub_dir in tqdm(os.listdir(root_dir)):
    sub_dir_path = os.path.join(root_dir, sub_dir)
    if not os.path.isdir(sub_dir_path):
        continue
    # print("Subdirpath:", os.path.join(root_dir, sub_dir))
    files1 = glob(root_dir+"/"+sub_dir+file_pattern_1)
    files2 = glob(root_dir+"/"+sub_dir+file_pattern_2)

    if files1 and files2:
        # Extract identified files
        file1 = files1[0]
        file2 = files2[0]
        
        # Prepare Output File
        output_dir = os.path.dirname(file1)
        output_file_with_subject = os.path.basename(sub_dir_path)+"_"+output_file_pattern
        
        # Prepare backup file name
        copyfile1 = file1.split('.nii')[0] + "_copy.nii"
        copyfile2 = file2.split('.nii')[0] + "_copy.nii"
        
        # Copy files to create backups
        # shutil.copyfile(file1, copyfile1)
        # shutil.copyfile(file2, copyfile2)
        
        # Identify the resampled file name
        resamp1 = copyfile1.split('.nii')[0]+"_resampled.nii"
        resamp2 = copyfile2.split('.nii')[0]+"_resampled.nii"
        
        # Attempt resampling to MNI space to fix bad headers
        subprocess.run(["flirt", "-in", copyfile1, "-ref", mni_template_path, "-out", resamp1], check=True)
        subprocess.run(["flirt", "-in", copyfile2, "-ref", mni_template_path, "-out", resamp2], check=True)
        
        # Identify the downsampled file name
        downfile1 = resamp1.split('.nii')[0]+"_mni152.nii"
        downfile2 = resamp2.split('.nii')[0]+"_mni152.nii"
        
        # Add the aligned files
        downsample_image(resamp1, downfile1)
        downsample_image(resamp2, downfile2)
        
        try:
            importer = GiiNiiFileImport(os.path.dirname(downfile1), file_pattern="*sim-binary_model-simbio_hemi-*_mni152*.nii")
            imports = importer.run()
            imports["summated"] = imports.iloc[:,0] + imports.iloc[:,1]
            display(imports["summated"].to_numpy())
            
            nifti_from_matrix(matrix=imports["summated"].to_numpy(), output_file=output_dir, output_name=output_file_with_subject, reference="MNI")
            
            # Clean up and remove the copy files. 
            os.remove(copyfile1)
            os.remove(copyfile2)
            os.remove(resamp1)
            os.remove(resamp2)            
            os.remove(downfile1)
            os.remove(downfile2)
            
            print(f"\n ***Processed: {sub_dir_path}")
            
        except subprocess.CalledProcessError as e:
            print(f"Error processing {sub_dir_path}: {e}")
    else:
        print(f"Missing file(s) in {sub_dir_path}")

  0%|          | 0/61 [00:00<?, ?it/s]

Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS034/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

  3%|▎         | 2/61 [00:00<00:07,  8.39it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS034/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS034
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS060/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

  5%|▍         | 3/61 [00:00<00:10,  5.79it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS060/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS060
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS058/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

  7%|▋         | 4/61 [00:00<00:12,  4.75it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS058/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS058
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS067/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

  8%|▊         | 5/61 [00:01<00:12,  4.45it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS067/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS067
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS051/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 10%|▉         | 6/61 [00:01<00:13,  4.17it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS051/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS051
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS069/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 11%|█▏        | 7/61 [00:01<00:13,  4.11it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS069/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS069
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS056/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 13%|█▎        | 8/61 [00:01<00:13,  3.94it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS056/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS056
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS035/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 15%|█▍        | 9/61 [00:02<00:13,  3.73it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS035/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS035
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS068/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 16%|█▋        | 10/61 [00:02<00:14,  3.60it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS068/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS068
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS057/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 18%|█▊        | 11/61 [00:02<00:13,  3.61it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS057/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS057
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS050/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 20%|█▉        | 12/61 [00:02<00:13,  3.62it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS050/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS050
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS066/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 21%|██▏       | 13/61 [00:03<00:12,  3.73it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS066/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS066
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS061/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 23%|██▎       | 14/61 [00:03<00:12,  3.74it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS061/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS061
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS043/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 25%|██▍       | 15/61 [00:03<00:12,  3.70it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS043/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS043
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS088/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 26%|██▌       | 16/61 [00:04<00:12,  3.66it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS088/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS088
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS044/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 28%|██▊       | 17/61 [00:04<00:12,  3.67it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS044/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS044
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS086/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 30%|██▉       | 18/61 [00:04<00:11,  3.67it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS086/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS086
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS072/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 31%|███       | 19/61 [00:04<00:11,  3.68it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS072/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS072
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS075/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 33%|███▎      | 20/61 [00:05<00:11,  3.61it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS075/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS075
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS081/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 34%|███▍      | 21/61 [00:05<00:11,  3.52it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS081/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS081
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS080/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 36%|███▌      | 22/61 [00:05<00:11,  3.54it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS080/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS080
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS074/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 38%|███▊      | 23/61 [00:05<00:10,  3.68it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS074/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS074
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS073/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 39%|███▉      | 24/61 [00:06<00:09,  3.73it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS073/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS073
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS087/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 41%|████      | 25/61 [00:06<00:09,  3.80it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS087/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS087
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS045/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 43%|████▎     | 26/61 [00:06<00:09,  3.78it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS045/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS045
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS042/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 44%|████▍     | 27/61 [00:06<00:08,  3.90it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS042/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS042
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS089/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 46%|████▌     | 28/61 [00:07<00:08,  3.99it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS089/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS089
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS029/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 48%|████▊     | 29/61 [00:07<00:07,  4.01it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS029/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS029
Missing file(s) in /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/logs
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS064/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 51%|█████     | 31/61 [00:07<00:05,  5.28it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS064/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS064
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS063/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 52%|█████▏    | 32/61 [00:07<00:06,  4.74it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS063/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS063
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS055/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 54%|█████▍    | 33/61 [00:08<00:06,  4.39it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS055/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS055
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS052/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 56%|█████▌    | 34/61 [00:08<00:06,  4.27it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS052/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS052
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS039/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 57%|█████▋    | 35/61 [00:08<00:06,  4.20it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS039/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS039
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS037/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 59%|█████▉    | 36/61 [00:09<00:06,  4.09it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS037/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS037
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS030/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 61%|██████    | 37/61 [00:09<00:05,  4.06it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS030/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS030
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS053/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 62%|██████▏   | 38/61 [00:09<00:05,  3.99it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS053/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS053
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS054/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 64%|██████▍   | 39/61 [00:09<00:05,  3.91it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS054/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS054
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS062/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 66%|██████▌   | 40/61 [00:10<00:05,  3.92it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS062/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS062
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS091/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 67%|██████▋   | 41/61 [00:10<00:05,  3.94it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS091/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS091
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS065/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 69%|██████▉   | 42/61 [00:10<00:04,  3.92it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS065/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS065
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS031/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 70%|███████   | 43/61 [00:10<00:04,  3.83it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS031/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS031
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS036/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 72%|███████▏  | 44/61 [00:11<00:04,  3.88it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS036/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS036
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS038/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 74%|███████▍  | 45/61 [00:11<00:04,  3.83it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS038/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS038
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS047/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 75%|███████▌  | 46/61 [00:11<00:03,  3.86it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS047/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS047
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS078/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 77%|███████▋  | 47/61 [00:11<00:03,  3.92it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS078/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS078
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS040/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 79%|███████▊  | 48/61 [00:12<00:03,  3.86it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS040/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS040
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS076/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 80%|████████  | 49/61 [00:12<00:03,  3.72it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS076/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS076
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS082/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 82%|████████▏ | 50/61 [00:12<00:02,  3.78it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS082/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS082
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS049/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 84%|████████▎ | 51/61 [00:12<00:02,  3.74it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS049/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS049
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS085/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 85%|████████▌ | 52/61 [00:13<00:02,  3.77it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS085/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS085
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS071/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 87%|████████▋ | 53/61 [00:13<00:02,  3.92it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS071/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS071
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS070/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 89%|████████▊ | 54/61 [00:13<00:01,  3.96it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS070/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS070
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS084/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 90%|█████████ | 55/61 [00:13<00:01,  4.03it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS084/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS084
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS083/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 92%|█████████▏| 56/61 [00:14<00:01,  4.02it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS083/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS083
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS077/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 93%|█████████▎| 57/61 [00:14<00:00,  4.06it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS077/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS077
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS048/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 95%|█████████▌| 58/61 [00:14<00:00,  4.08it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS048/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS048
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS041/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 97%|█████████▋| 59/61 [00:14<00:00,  4.01it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS041/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS041
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS046/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

 98%|█████████▊| 60/61 [00:15<00:00,  4.04it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS046/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS046
Attempting to import from: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS079/stimulations/MNI152NLin2009bAsym/gs_2023Aysu/*sim-binary_model-simbio_hemi-*_mni152*.nii


array([0., 0., 0., ..., 0., 0., 0.])

100%|██████████| 61/61 [00:15<00:00,  3.96it/s]

Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS079/stimulations/MNI152NLin2009bAsym/gs_2023Aysu

 ***Processed: /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/Queensland_PD_DBS_STN/BIDSdata/derivatives/leaddbs/sub-LeadDBS079
