## User Instructions
This is a program which will create R-Maps. These are used to correlate a voxel to a continuous outcome measure.
As it stands, this software employs Pearson Correlation Coefficients, which imply it will be best to have a continuous outcome on a percent scale. If you would like to do otherwise, a Spearman Correlation is possible. 

The software will walk you through everything. 

Files are expected to follow a BIDS naming convention. 
Subject IDs are expected in the input CSV and are expected to share the same naming convention as the nifti files themselves.

**Function Definitions**
Functions defined within noteook to avoid 

Imports

In [ ]:
import pandas as pd
import numpy as np

Save Information

-Enter the directory you would like to save to

In [209]:
out_dir = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week'

---

**Instructions**: Please fill out the `path` and `file_pattern` variables. 

The file_path is the shared base directory holding all files. ie) blah/blah/blah/BIDS

The file_pattern is the shared naming architectur in all files ie)  * / * / * subT1 * .nii

---

In [210]:
# What is the shared path to the folder/csv containing the nifti files/files paths for the neuroimaging files?
path_1 = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/BIDS_Dataset'

#What is the shared file architecture of your neuroimaging files after the base path?
file_pattern = '*/*/*stat-t_conn.nii.gz'

In [211]:
#-----------------DO NOT TOUCH--------------------------------------------------------
import os
from calvin_utils.file_utils.import_matrices import import_matrices_from_folder
df_1 = import_matrices_from_folder(path_1, file_pattern=file_pattern)
df_1

I will search:  /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/BIDS_Dataset/*/*/*stat-t_conn.nii.gz


sub-026_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-088_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-043_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-044_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-072_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-075_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                                    0.0   
902627                                    0.0   
902628                                    0.0   

        sub-081_tome-yeo1k_stat-t_conn.nii.gz  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
902624                                    0.0   
902625                                    0.0   
902626                           

**Extract Subject ID From File Names**
Using the example filenames that have been printed above, please define a general string:
1) Preceding the subject ID. For example in 04-mwp1glanat_resampled.nii, this is " "
2) Proceeding the subject ID. For example in 04-mwp1glanat_resampled.nii, this is "-mwp1"

In [212]:
from calvin_utils.file_utils.dataframe_utilities import extract_and_rename_subject_id

def preprocess_names(df, string_preceding_id, string_proceeding_id, cols=True):
    """
    Preprocess the given dataframe by extracting and renaming the subject ID, 
    then transposing the dataframe.

    Parameters:
    - df: The dataframe to preprocess.
    - string_preceding_id: String preceding the subject ID.
    - string_proceeding_id: String proceeding the subject ID.

    Returns:
    - The preprocessed dataframe.
    """
    split_command_dict = {string_preceding_id: 1, string_proceeding_id: 0}
    if cols:
        df = extract_and_rename_subject_id(dataframe=df, split_command_dict=split_command_dict).transpose()
    else:
        df = extract_and_rename_subject_id(dataframe=df, split_command_dict=split_command_dict)
    df.index.name = 'subject'
    return df


In [213]:
string_preceding_id = 'sub-'
string_proceeding_id = '_tome'

In [214]:
df_1 = preprocess_names(df_1, string_preceding_id, string_proceeding_id)
df_1

0       1       2       3       4       5       6       7       \
subject                                                                   
026         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
088         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
043         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
044         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
072         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
038         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
053         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
098         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
062         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
065         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

         8       9       ...  902619  902620  902621  902622  902623  902624  \
subject                  ...                                                   
026         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
088         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
043         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
044         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
072         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
038         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
053         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
098         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
062         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
065         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

         902625  902626  902627  902628  
subject                                  
026         0.0     0.0     0.0     0.0  
088         0.0     0.0     0.0     0.0  
043         0.0     0.0     0.0     0.0  
044         0.0     0.0     0.0     0.0  
072         0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
038         0.0     0.0     0.0     0.0  
053         0.0     0.0     0.0     0.0  
098         0.0     0.0     0.0     0.0  
062         0.0     0.0     0.0     0.0  
065         0.0     0.0     0.0     0.0  

[135 rows x 902629 columns]

Define the path to the CSV which has your clinical information

In [238]:
path_2 = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/Study_Metadata/Behavior_FactorAnalysis_week.csv'

In [239]:
# Import a CSV with the clinical data of interest
df_2 = pd.read_csv(path_2)
df_2

subject  Language  MotorL  MotorR  AttentionVF  AttentionAve  \
0    FCS_024   -2.3822     NaN     NaN      -2.9237       -0.2572   
1    FCS_025       NaN     NaN     NaN          NaN           NaN   
2    FCS_026    0.4098     NaN     NaN       0.8293       -1.0631   
3    FCS_027   -2.2827     NaN     NaN       0.4972       -0.9441   
4    FCS_028       NaN     NaN     NaN          NaN           NaN   
..       ...       ...     ...     ...          ...           ...   
168  FCS_192   -3.2569  0.7975  0.5861          NaN           NaN   
169  FCS_193    0.7302  0.6155 -0.4802       0.2607        0.6090   
170  FCS_194   -2.9641 -0.4978 -2.8667          NaN           NaN   
171  FCS_195    0.5864 -2.3491  0.0868          NaN           NaN   
172  FCS_196    0.6699  0.4334 -0.4434       0.3186        0.5573   

     AttentionValDis  MemoryS  MemoryV  Motor_IC  ...  Language_W2  \
0             0.8242      NaN      NaN       NaN  ...       1.3764   
1                NaN      NaN      NaN       NaN  ...          NaN   
2            -0.4577      NaN      NaN       NaN  ...       0.4190   
3             0.2406      NaN      NaN       NaN  ...       0.4234   
4                NaN      NaN      NaN       NaN  ...          NaN   
..               ...      ...      ...       ...  ...          ...   
168              NaN      NaN      NaN    0.8521  ...      -2.3366   
169          -0.0414   0.9896   1.2775    0.2372  ...      -0.6949   
170              NaN      NaN      NaN   -1.7035  ...      -0.7164   
171              NaN  -1.2845   0.4588   -1.7040  ...      -0.1320   
172           0.3310   0.4851   0.7808    0.3529  ...      -0.5551   

     Attention_IC_VF  Attention_IC2  Attention_IC3  Group1  Group2  Group3  \
0            -2.3983        -1.0733         0.6471     NaN     NaN     NaN   
1                NaN            NaN            NaN     NaN     NaN     NaN   
2            -0.6535         0.5219        -0.5082     NaN     NaN     NaN   
3             0.0392         0.0474        -1.6694     NaN     NaN     NaN   
4                NaN            NaN            NaN     NaN     NaN     NaN   
..               ...            ...            ...     ...     ...     ...   
168              NaN            NaN            NaN     NaN     NaN     NaN   
169           0.6355        -0.1315        -0.2397  1.1814  0.3105 -0.8401   
170              NaN            NaN            NaN     NaN     NaN     NaN   
171              NaN            NaN            NaN     NaN     NaN     NaN   
172           0.5945        -0.1507         0.2048  0.7454  0.1953 -0.5723   

     VisualL  VisualR  Visual_IC  
0        NaN      NaN        NaN  
1        NaN      NaN        NaN  
2        NaN      NaN        NaN  
3        NaN      NaN        NaN  
4        NaN      NaN        NaN  
..       ...      ...        ...  
168  -1.0417 -21.2143   -20.1726  
169  -1.1786  -1.7917    -0.6131  
170      NaN      NaN        NaN  
171      NaN      NaN        NaN  
172  -2.0714  -2.7560    -0.6845  

[173 rows x 21 columns]

In [241]:
string_preceding_id = 'FCS_'
string_proceeding_id = ''

It is expected there is a columnc called which has subject information in it. The information in this column must correspond in the dataframe above. If it does not exist, add it to your CSV before proceeding. 

Define the column below using:

subject_colum = 

In [243]:
import os
from calvin_utils.statistical_utils.voxelwise_statistical_testing import generate_r_map
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti

def reset_index_if_subject_is_index(df, subject_column):
    if subject_column in df.index.names:
        df.reset_index(inplace=True)
        # Reorder columns to make 'subject' the first column
        cols = [subject_column] + [col for col in df.columns if col != subject_column]
        df = df[cols]
    return df

def process_and_generate_maps(df_1, df_2, subject_column, out_dir):
    """
    Process the given dataframes, and generate maps based on the columns.

    Parameters:
    - df_1: First dataframe.
    - df_2: Second dataframe.
    - subject_column: The column name referring to the subject.
    - out_dir: The output directory to save the generated maps.
    """
    # Check if 'subject' is in the index or columns for df_1
    if subject_column in df_1.index.names:
        df_1 = reset_index_if_subject_is_index(df_1, subject_column)
    if subject_column in df_2.index.names:
        df_2 = reset_index_if_subject_is_index(df_2, subject_column)

    # Iterate over column, avoiding the one with subject id in it
    for colname in [col for col in df_2.columns if col != subject_column]:
        print(f'Working on {colname}')
        merged_df = df_2[[colname, subject_column]].merge(df_1, on=subject_column, how='inner').set_index(subject_column)
        
        # Remove any rows with NaN values
        merged_df.dropna(inplace=True)

        r_df, p_df, r_squared_df = generate_r_map(merged_df, mask_path=None)

        view_and_save_nifti(p_df, os.path.join(out_dir, 'p_map', colname))
        view_and_save_nifti(r_df, os.path.join(out_dir, 'r_map', colname))
        view_and_save_nifti(r_squared_df, os.path.join(out_dir, 'r_squared_map', colname))
    return merged_df


What is the name of the column that contains your subject labels?

In [244]:
subject_column = 'subject'

In [245]:
import os
df_2[subject_column] = df_2[subject_column].str.split(string_preceding_id).str[1]
merged_df = process_and_generate_maps(df_1.copy(), df_2.copy(), subject_column, out_dir)

Working on Language
Dataframes have been masked such that their shapes are:  (124, 225222)


100%|██████████| 225222/225222 [00:32<00:00, 6969.26it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Language
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Language
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Language
Working on MotorL
Dataframes have been masked such that their shapes are:  (117, 225222)


100%|██████████| 225222/225222 [00:32<00:00, 6979.20it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/MotorL
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/MotorL
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/MotorL
Working on MotorR
Dataframes have been masked such that their shapes are:  (117, 225222)


100%|██████████| 225222/225222 [00:31<00:00, 7243.92it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/MotorR
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/MotorR
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/MotorR
Working on AttentionVF
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:31<00:00, 7241.28it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/AttentionVF
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/AttentionVF
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/AttentionVF
Working on AttentionAve
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:30<00:00, 7496.29it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/AttentionAve
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/AttentionAve
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/AttentionAve
Working on AttentionValDis
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:30<00:00, 7304.57it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/AttentionValDis
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/AttentionValDis
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/AttentionValDis
Working on MemoryS
Dataframes have been masked such that their shapes are:  (97, 225222)


100%|██████████| 225222/225222 [00:30<00:00, 7284.74it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/MemoryS
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/MemoryS
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/MemoryS
Working on MemoryV
Dataframes have been masked such that their shapes are:  (97, 225222)


100%|██████████| 225222/225222 [00:31<00:00, 7199.96it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/MemoryV
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/MemoryV
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/MemoryV
Working on Motor_IC
Dataframes have been masked such that their shapes are:  (117, 225222)


100%|██████████| 225222/225222 [00:31<00:00, 7038.84it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Motor_IC
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Motor_IC
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Motor_IC
Working on Language_W1
Dataframes have been masked such that their shapes are:  (124, 225222)


100%|██████████| 225222/225222 [00:32<00:00, 6825.62it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Language_W1
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Language_W1
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Language_W1
Working on Language_W2
Dataframes have been masked such that their shapes are:  (124, 225222)


100%|██████████| 225222/225222 [00:32<00:00, 6915.45it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Language_W2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Language_W2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Language_W2
Working on Attention_IC_VF
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:33<00:00, 6814.94it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Attention_IC_VF
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Attention_IC_VF
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Attention_IC_VF
Working on Attention_IC2
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:31<00:00, 7208.47it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Attention_IC2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Attention_IC2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Attention_IC2
Working on Attention_IC3
Dataframes have been masked such that their shapes are:  (100, 225222)


100%|██████████| 225222/225222 [00:33<00:00, 6789.69it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Attention_IC3
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Attention_IC3
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Attention_IC3
Working on Group1
Dataframes have been masked such that their shapes are:  (66, 225222)


100%|██████████| 225222/225222 [00:30<00:00, 7486.68it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Group1
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Group1
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Group1
Working on Group2
Dataframes have been masked such that their shapes are:  (66, 225222)


100%|██████████| 225222/225222 [00:29<00:00, 7665.52it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Group2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Group2
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Group2
Working on Group3
Dataframes have been masked such that their shapes are:  (66, 225222)


100%|██████████| 225222/225222 [00:30<00:00, 7425.93it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Group3
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Group3
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Group3
Working on VisualL
Dataframes have been masked such that their shapes are:  (64, 225222)


100%|██████████| 225222/225222 [00:28<00:00, 7844.29it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/VisualL
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/VisualL
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/VisualL
Working on VisualR
Dataframes have been masked such that their shapes are:  (64, 225222)


100%|██████████| 225222/225222 [00:29<00:00, 7654.38it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/VisualR
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/VisualR
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/VisualR
Working on Visual_IC
Dataframes have been masked such that their shapes are:  (64, 225222)


100%|██████████| 225222/225222 [00:28<00:00, 7867.83it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/p_map/Visual_IC
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_map/Visual_IC
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/corbetta/derivatives/symptom_networks/one_week/r_squared_map/Visual_IC


Your R-Maps have all been generated. Consider adding Calvin as a collaborator if this was useful!

-- Calvin

## Optional - Perform Delta R-Map and Permute it for Significance

**Calculate the Observed Delta-R Map Between 2 Populations**

In [ ]:
from calvin_utils.statistical_utils.voxelwise_statistical_testing import generate_delta_r_map
delta_matrix = merged_df.copy()
observed_delta_r_map = generate_delta_r_map(delta_matrix, threshold_of_interest=65, column_of_interest='Age at DOS')

In [ ]:
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti
view_and_save_nifti(observed_delta_r_map, (out_dir+'/over_vs_under_65_delta_r_map'))

## Calculate the Empiric Delta-R Map Distribution 
### Note, this permutes the label of the population without permuting the neuroimaging data.
### Therefore, we are testing if the separation of the r-maps is significantly due to the variable of interest. 

In [ ]:
from calvin_utils.statistical_utils.voxelwise_statistical_testing import permuted_patient_label_delta_r_map
from calvin_utils.file_utils.print_suppression import HiddenPrints
n_permutations = 2
column_of_interest = 'Age at DOS'
threshold_of_interest = 65
with HiddenPrints():
    p_count_df = permuted_patient_label_delta_r_map(dataframe_to_permute=merged_df, 
                                                observed_delta_r_map=observed_delta_r_map, 
                                                column_of_interest=column_of_interest, 
                                                threshold_of_interest=threshold_of_interest, 
                                                n_permutations=n_permutations)

In [ ]:
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti
view_and_save_nifti(p_values_df, (out_dir+'/over_vs_under_65_delta_r_map_p_values_df'))

Enjoy

--Calvin