## User Instructions
This is a program which will create R-Maps. These are used to correlate a voxel to a continuous outcome measure.
As it stands, this software employs Pearson Correlation Coefficients, which imply it will be best to have a continuous outcome on a percent scale. If you would like to do otherwise, a Spearman Correlation is possible. 

The software will walk you through everything. 

Files are expected to follow a BIDS naming convention. 
Subject IDs are expected in the input CSV and are expected to share the same naming convention as the nifti files themselves.

**Function Definitions**
Functions defined within noteook to avoid 

Imports

In [1]:
import pandas as pd
import numpy as np

Save Information

-Enter the directory you would like to save to

In [2]:
out_dir = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet'

---

**Instructions**: Please fill out the `path` and `file_pattern` variables. 

The file_path is the shared base directory holding all files. ie) blah/blah/blah/BIDS

The file_pattern is the shared naming architectur in all files ie)  * / * / * subT1 * .nii

---

In [3]:
# What is the shared path to the folder/csv containing the nifti files/files paths for the neuroimaging files?
path_1 = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/connectivity_data/vta_published_t_connectivity'

#What is the shared file architecture of your neuroimaging files after the base path?
file_pattern = '*.nii'

In [4]:
#-----------------DO NOT TOUCH--------------------------------------------------------
import os
from calvin_utils.file_utils.import_matrices import import_matrices_from_folder
df_1 = import_matrices_from_folder(path_1, file_pattern=file_pattern)
df_1

I will search:  /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/connectivity_data/vta_published_t_connectivity/*.nii


116_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                                                     0.0   
...                                                   ...   
902624                                                0.0   
902625                                                0.0   
902626                                                0.0   
902627                                                0.0   
902628                                                0.0   

        1203_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0    
1                                                     0.0    
2                                                     0.0    
3                                                     0.0    
4                                                     0.0    
...                                                   ...    
902624                                                0.0    
902625                                                0.0    
902626                                                0.0    
902627                                                0.0    
902628                                                0.0    

        139_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                                                     0.0   
...                                                   ...   
902624                                                0.0   
902625                                                0.0   
902626                                                0.0   
902627                                                0.0   
902628                                                0.0   

        147_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                                                     0.0   
...                                                   ...   
902624                                                0.0   
902625                                                0.0   
902626                                                0.0   
902627                                                0.0   
902628                                                0.0   

        135_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                                                     0.0   
...                                                   ...   
902624                                                0.0   
902625                                                0.0   
902626                                                0.0   
902627                                                0.0   
902628                                                0.0   

        101_vat_seed_compound_fMRI_efield_func_seed_T.nii  \
0                                                     0.0   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                         

**Extract Subject ID From File Names**
Using the example filenames that have been printed above, please define a general string:
1) Preceding the subject ID. For example in 04-mwp1glanat_resampled.nii, this is " "
2) Proceeding the subject ID. For example in 04-mwp1glanat_resampled.nii, this is "-mwp1"

In [5]:
from calvin_utils.file_utils.dataframe_utilities import extract_and_rename_subject_id

def preprocess_df1(df_1, string_preceding_id, string_proceeding_id):
    """
    Preprocess the given dataframe by extracting and renaming the subject ID, 
    then transposing the dataframe.

    Parameters:
    - df_1: The dataframe to preprocess.
    - string_preceding_id: String preceding the subject ID.
    - string_proceeding_id: String proceeding the subject ID.

    Returns:
    - The preprocessed dataframe.
    """
    split_command_dict = {string_preceding_id: 1, string_proceeding_id: 0}
    df_1 = extract_and_rename_subject_id(dataframe=df_1, split_command_dict=split_command_dict).transpose()
    df_1.index.name = 'subject'
    display(df_1)
    return df_1


In [6]:
string_preceding_id = ' '
string_proceeding_id = '_vat'

In [7]:
df_1 = preprocess_df1(df_1, string_preceding_id, string_proceeding_id)

0       1       2       3       4       5       6       7       \
subject                                                                   
116         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1203        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
139         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
147         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
135         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
101         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
150         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
122         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1202        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
146         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
138         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
134         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
123         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
149         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
137         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
118         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
114         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
145         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1201        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
120         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
103         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
119         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
148         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
144         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
115         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
121         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
102         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
105         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
109         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
126         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
143         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
112         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
131         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
104         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
127         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
108         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
113         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
142         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
130         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
124         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
128         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
107         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
133         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
141         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
110         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
125         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
106         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
129         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
111         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
140         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

         8       9       ...  902619  902620  902621  902622  902623  902624  \
subject                  ...

Define the path to the CSV which has your clinical information

In [8]:
path_2 = '/Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet.csv'

In [9]:
# Import a CSV with the clinical data of interest
df_2 = pd.read_csv(path_2)
df_2

subject_id  Age  Baseline  % Change from baseline (ADAS-Cog11)  \
0          101   62      28.0                           -21.428571   
1          102   77      22.0                           -36.363636   
2          103   76      19.0                           -78.947368   
3          104   65      17.0                          -129.411765   
4          105   50      19.0                           -10.526316   
5          106   66      13.0                           -38.461538   
6          107   64      13.0                           -15.384615   
7          108   60      24.0                           -29.166667   
8          109   72      23.0                           -30.434783   
9          110   72      13.0                           -84.615385   
10         111   62      12.0                            41.666667   
11         112   69      15.0                             9.333333   
12         113   69      15.0                           -60.000000   
13         114   67      31.0                           -16.129032   
14         115   60      29.0                           -48.275862   
15         116   67      19.0                           -36.842105   
16         118   52      32.0                            -3.125000   
17         119   75      16.0                           -81.250000   
18         120   68      18.0                           -27.777778   
19         121   72      23.0                            -4.347826   
20         122   58      15.0                          -140.000000   
21         123   47      22.0                            54.545455   
22         124   61      16.0                           -18.750000   
23         125   73      16.0                           -37.500000   
24         126   69      21.0                          -100.000000   
25         127   74      17.0                           -76.470588   
26         128   72      24.0                           -20.833333   
27         129   69      28.0                           -35.714286   
28         130   66      14.0                            -7.142857   
29         131   68      20.0                           -40.000000   
30         133   74      16.0                             6.250000   
31         134   66      17.0                            29.411765   
32         135   57      35.0                           -45.714286   
33         137   57      22.0                           -77.272727   
34         138   72      21.0                            -9.523810   
35         139   58      17.0                          -105.882353   
36         140   73      22.0                            18.181818   
37         141   72      19.0                             0.000000   
38         142   77      18.0                             5.555556   
39         143   71      16.0                             6.250000   
40         144   79      13.0                           -61.538462   
41         145   74      18.0                             5.555556   
42         146   76      11.0                           -54.545455   
43         147   59      21.0                            -4.761905   
44         148   51      13.0                          -207.692308   
45         149   77      10.0                           -90.000000   
46         150   71      22.0                            13.636364   
47        1201   78      19.6                            -7.142857   
48        1202   74      13.3                            -2.255639   
49        1203   76      24.0                           -73.333333   

    Subiculum Connectivity  Abs Stim Composite Atophy SpCorrel  \
0                56.864683                           -0.032752   
1                52.970984                            0.017825   
2                62.459631                            0.007157   
3                59.611631                           -0.041364   
4                57.928350                            0.023781   
5                63.323903           

It is expected there is a columnc called which has subject information in it. The information in this column must correspond in the dataframe above. If it does not exist, add it to your CSV before proceeding. 

Define the column below using:

subject_colum = 

In [10]:
import os
from calvin_utils.statistical_utils.voxelwise_statistical_testing import generate_r_map
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti

def process_and_generate_maps(df_1, df_2, subject_column, out_dir):
    """
    Process the given dataframes, and generate maps based on the columns.

    Parameters:
    - df_1: First dataframe.
    - df_2: Second dataframe.
    - subject_column: The column name referring to the subject.
    - out_dir: The output directory to save the generated maps.
    """
    # Extract and set subject IDs from paths
    try:
        df_2['subject'] = df_2[subject_column].apply(lambda path: os.path.basename(path).split('_')[1])
    except:
        df_2['subject'] = df_2[subject_column].astype(str)

    # Iterate over columns starting from the second, as the first is the subject ID
    for colname in df_2.columns:
        merged_df = df_2[[colname, 'subject']].merge(df_1, on='subject', how='inner').set_index('subject')
        
        # Remove any rows with NaN values
        merged_df.dropna(inplace=True)

        r_df, p_df, r_squared_df = generate_r_map(merged_df, mask_path=None)

        view_and_save_nifti(p_df, os.path.join(out_dir, 'p_map', colname))
        view_and_save_nifti(r_df, os.path.join(out_dir, 'r_map', colname))
        view_and_save_nifti(r_squared_df, os.path.join(out_dir, 'r_squared_map', colname))


In [11]:
import os
# What is the name of the column that contains your subject labels?
subject_column = 'subject_id'

In [12]:
process_and_generate_maps(df_1, df_2, subject_column, out_dir)


Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:28<00:00, 7961.39it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Age
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Age
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Age
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8460.56it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Baseline
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Baseline
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Baseline
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8585.40it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/% Change from baseline (ADAS-Cog11)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/% Change from baseline (ADAS-Cog11)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/% Change from baseline (ADAS-Cog11)
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8483.18it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Subiculum Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Subiculum Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Subiculum Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8561.81it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Abs Stim Composite Atophy SpCorrel
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Abs Stim Composite Atophy SpCorrel
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Abs Stim Composite Atophy SpCorrel
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8522.79it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Raw Stim Composite Atrophy SpCorrel
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Raw Stim Composite Atrophy SpCorrel
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Raw Stim Composite Atrophy SpCorrel
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:25<00:00, 8695.16it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Frontal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Frontal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Frontal Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8631.47it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Insula Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Insula Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Insula Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8581.73it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Temporal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Temporal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Temporal Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8618.51it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Cerebellar Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Cerebellar Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Cerebellar Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8534.84it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Subiculum Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Subiculum Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Subiculum Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8586.07it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Occipital Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Occipital Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Occipital Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8551.67it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Parietal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Parietal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Parietal Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8374.15it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Total Atrophy Voxels
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Total Atrophy Voxels
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Total Atrophy Voxels
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8581.74it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Visual Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Visual Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Visual Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8586.75it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Somatomotor Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Somatomotor Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Somatomotor Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8552.37it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Dorsal Attention Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Dorsal Attention Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Dorsal Attention Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8614.17it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Ventral Attention Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Ventral Attention Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Ventral Attention Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8568.64it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Limbic Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Limbic Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Limbic Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8557.77it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Frontoparietal Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Frontoparietal Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Frontoparietal Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8455.53it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Default Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Default Connectivity
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Default Connectivity
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8494.68it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Default Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Default Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Default Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8540.06it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Visual Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Visual Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Visual Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:25<00:00, 8705.05it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Limbic Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Limbic Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Limbic Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:25<00:00, 8740.97it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Somatomotor Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Somatomotor Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Somatomotor Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:25<00:00, 8712.35it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Dorsal Attention Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Dorsal Attention Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Dorsal Attention Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:25<00:00, 8718.37it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Ventral Attention Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Ventral Attention Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Ventral Attention Atrophy
Dataframes have been masked such that their shapes are:  (50, 225222)


100%|██████████| 225222/225222 [00:26<00:00, 8498.74it/s]


(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(902629,)
[ 93491  93492  93493 ... 798282 798283 798373]
Data has been unmasked to shape:  (1, 902629)
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/p_map/Frontoparietal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_map/Frontoparietal Atrophy
(91, 109, 91)
(1, 902629)
Image saved to: 
 /Users/cu135/Dropbox (Partners HealthCare)/resources/datasets/BIDS_AD_DBS_FORNIX/clinical_analyses/ses-01/sub-all/all_data/all_metadata_spreadsheet/r_squared_map/Frontoparietal Atrophy


ValueError: The column label 'subject' is not unique.

In [ ]:
# reinsert = df_2.pop(subject_column)
# df_2['subject'] = reinsert

# #----------------------------------------------------------------END USER INPUTS----------------------------------------------------------------
# analysis_name = 'r_maps'

# for colname in df_2.columns[column_outcomes_start_in:]:
#     column_to_merge_on = colname
#     path_list = df_2.loc[:, subject_column].to_list()
#     try:
#         basename_path_list = [os.path.basename(path).split('_')[1] for path in path_list]
#     except:
#         basename_path_list = [str(path) for path in path_list]
#     df_2['subject'] = basename_path_list
#     df_2['subject']
    
#     prep_df = df_2.copy()
#     final_df = df_2.loc[:, [column_to_merge_on, 'subject']].merge(df_1, on='subject', right_index=False)
#     merged_df = final_df.set_index('subject')
#     columns_to_remove = None

#     #Remove undesirable columns
#     final_df = merged_df.copy()
#     final_df = final_df.dropna()
#     try:
#         final_df.pop(columns_to_remove)
#     except:
#         print('Soft error raised: could not find column %s:' % columns_to_remove)
#     from calvin_utils.statistical_utils.voxelwise_statistical_testing import generate_r_map
#     r_df, p_df, r_squared_df = generate_r_map(final_df, mask_path=None)
#     from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti
#     view_and_save_nifti(p_df, (out_dir+f'/p_map/{column_to_merge_on}'))
#     view_and_save_nifti(r_df, (out_dir+f'/r_map/{column_to_merge_on}'))
#     view_and_save_nifti(r_squared_df, (out_dir+f'/r_squared_map/{column_to_merge_on}'))

## Optional - Perform Delta R-Map and Permute it for Significance

**Calculate the Observed Delta-R Map Between 2 Populations**

In [ ]:
from calvin_utils.statistical_utils.voxelwise_statistical_testing import generate_delta_r_map
delta_matrix = merged_df.copy()
observed_delta_r_map = generate_delta_r_map(delta_matrix, threshold_of_interest=65, column_of_interest='Age at DOS')

In [ ]:
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti
view_and_save_nifti(observed_delta_r_map, (out_dir+'/over_vs_under_65_delta_r_map'))

## Calculate the Empiric Delta-R Map Distribution 
### Note, this permutes the label of the population without permuting the neuroimaging data.
### Therefore, we are testing if the separation of the r-maps is significantly due to the variable of interest. 

In [ ]:
from calvin_utils.statistical_utils.voxelwise_statistical_testing import permuted_patient_label_delta_r_map
from calvin_utils.file_utils.print_suppression import HiddenPrints
n_permutations = 2
column_of_interest = 'Age at DOS'
threshold_of_interest = 65
with HiddenPrints():
    p_count_df = permuted_patient_label_delta_r_map(dataframe_to_permute=merged_df, 
                                                observed_delta_r_map=observed_delta_r_map, 
                                                column_of_interest=column_of_interest, 
                                                threshold_of_interest=threshold_of_interest, 
                                                n_permutations=n_permutations)

In [ ]:
from calvin_utils.nifti_utils.generate_nifti import view_and_save_nifti
view_and_save_nifti(p_values_df, (out_dir+'/over_vs_under_65_delta_r_map_p_values_df'))

Enjoy

--Calvin